### ISSUE TITLE
Optimization and webpack caching

### ISSUE THREAD

**Issue by tmeasday** [tmeasday/storybook-skeleton#1]
What can we do to further improve the build performance of this project?

**Comment by bebraw** [comment]
I think the test here is to set webpack cache use the file system. Reference: https://webpack.js.org/configuration/other-options/#cache . It's defaulting to memory cache by default in development mode but we could set it to file system during a production build specifically. To test, we'll first have to generate non-cached builds and then cached builds. Before the first step, it should remove webpack cache directory.
