### ISSUE TITLE
Try using a globbed entry plugin rather than `require.context`

### ISSUE THREAD

**Issue by tmeasday** [tmeasday/storybook-skeleton#4]
I'm actually not sure there is a big problem with using `require.context()` (see snowpack example) but open to ideas here if it helps.

**Comment by bebraw** [comment]
I would skip this one since you found a good solution already with `import()` as that's standard.

**Comment by tmeasday** [comment]
Is there a way to tell webpack about every file you might dynamically `import` ahead of time?

The way that code works is we do:

```js
import data from 'path/to/stories.json';

// later
await import(data[someStoryId].parameters.filename)
```

I think webpack might not even allow that?

We'll be generating the json data, possibly in a separate process, possibly with webpack, IDK.

In Snowpack the above was fine because as a ESM bundler it just serves up any filename as you request it. I'm not quite sure what it would do if you tried to build a production bundle/set of bundles though. I suppose it would have the same problem.

**Comment by bebraw** [comment]
It cannot be completely dynamic but partially (similar to require.context). I have an example at https://survivejs.com/webpack/techniques/dynamic-loading/#dynamic-paths-with-a-dynamic-import .

**Comment by tmeasday** [comment]
Let's close this in favour of https://github.com/tmeasday/storybook-skeleton/issues/19
