### ISSUE TITLE
Try turning sourcemaps on

### ISSUE THREAD

**Issue by tmeasday** [tmeasday/storybook-skeleton#6]
How does adding sourcemaps influence metrics?

**Comment by bebraw** [comment]
I wonder which type(s) to test. See https://webpack.js.org/configuration/devtool/#devtool. What's the default in Storybook projects?

**Comment by tmeasday** [comment]
Looks like `cheap-module-source-map`: https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack5/src/preview/iframe-webpack.config.ts#L118
